spring:
  application:
    name: ct-image-processor-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
server:
  port: 8082
orthanc:
  server:
    url: ${ORTHANC_URL}
fhir:
  server:
    url: ${FHIR_URL}